### ISSUE TITLE
doing "importing a new pattern library from a Github repo in your pattern library" step/issue

### ISSUE THREAD

**Issue by rebmullin** [pattern-library/generator-pattern-library#11]
hey @scottnath  - not sure if i am missing a step but i was having some issues with step 3 and 4 in this section:
1. First tried this way:
   `gulp patterns-import-all` then `gulp serve`
   and get the following response:
   `>gulp serve
   [14:56:31] Using gulpfile ~/Desktop/gen-new/gulpfile.js
   [14:56:31] Starting 'serve'...
   [14:56:31] Starting 'glob-inject-sass-all'...
   [14:56:31] Starting 'glob-inject-sass-npm-base'...
   [14:56:31] Starting 'glob-inject-js-all'...
   [14:56:31] Starting 'glob-inject-js-npm-base'...
   [14:56:31] Finished 'glob-inject-js-all' after 2.95 ms
   [14:56:31] Finished 'glob-inject-sass-all' after 15 ms
   [14:56:31] Starting 'glob-inject-sass-all'...
   [14:56:31] Finished 'glob-inject-sass-all' after 131 μs
   [14:56:31] Starting 'sass'...
   [14:56:31] gulp-inject Nothing to inject into style.scss.
   [14:56:31] gulp-inject Nothing to inject into _01-foot.twig.
   [14:56:31] Finished 'glob-inject-sass-npm-base' after 36 ms
   [14:56:31] Starting 'glob-inject-sass-npm-scottnath'...
   [14:56:31] Finished 'glob-inject-js-npm-base' after 27 ms
   [14:56:31] Starting 'glob-inject-js-npm-scottnath'...
   [14:56:31] Finished 'sass' after 25 ms
   [14:56:31] Starting 'patternlab-build-public'...
   [14:56:31] gulp-inject Nothing to inject into style.scss.
   [14:56:31] gulp-inject Nothing to inject into _01-foot.twig.
   [14:56:31] Finished 'glob-inject-sass-npm-scottnath' after 17 ms
   [14:56:31] Starting 'global-assets-import-sass'...
   [14:56:31] Finished 'global-assets-import-sass' after 4.85 ms
   [14:56:31] Starting 'glob-inject-sass-global-assets'...
   [14:56:31] Finished 'glob-inject-js-npm-scottnath' after 23 ms
   [14:56:31] Starting 'global-assets-import-js'...
   [14:56:31] Finished 'global-assets-import-js' after 2.46 ms
   [14:56:31] Starting 'glob-inject-js-global-assets'...
   [14:56:31] gulp-inject Nothing to inject into style.scss.
   [14:56:31] gulp-inject Nothing to inject into _01-foot.twig.
   [14:56:31] Finished 'glob-inject-sass-global-assets' after 9.27 ms
   [14:56:31] Starting 'glob-inject-sass-local'...
   [14:56:31] Finished 'glob-inject-js-global-assets' after 6.49 ms
   [14:56:31] Starting 'glob-inject-js-local'...
   [14:56:31] gulp-inject Nothing to inject into style.scss.
   [14:56:31] gulp-inject Nothing to inject into _01-foot.twig.
   [14:56:31] Finished 'glob-inject-sass-local' after 6.79 ms
   [14:56:31] Finished 'glob-inject-js-local' after 4.41 ms
   [14:56:31] 'patternlab-build-public' errored after 122 ms
   [14:56:31] Error: 1
   at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
   at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
   at Gulp.emit (events.js:129:20)
   at Gulp.Orchestrator._emitTaskDone (/Users/rebeccamullin/Desktop/gen-new/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
   at /Users/rebeccamullin/Desktop/gen-new/node_modules/gulp/node_modules/orchestrator/index.js:275:23
   at finish (/Users/rebeccamullin/Desktop/gen-new/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
   at ChildProcess.cb (/Users/rebeccamullin/Desktop/gen-new/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
   at ChildProcess.emit (events.js:110:17)
   at maybeClose (child_process.js:1015:16)
   at Socket.<anonymous> (child_process.js:1183:11)
   [14:56:31] Error in plugin 'run-sequence'
   Message:
   An error occured in task 'patternlab-build-public'.` http://grab.by/KN3S

or screenshot http://grab.by/KN40
1. Also tried the alternate way mentioned but i get this response:
   `>gulp patterns-import-scottnath
   [14:56:46] Using gulpfile ~/Desktop/gen-new/gulpfile.js
   [14:56:46] Task 'patterns-import-scottnath' is not in your gulpfile
   [14:56:46] Please check the documentation for proper gulpfile formatting`

please let me know if i am missing any steps..

thanks

**Comment by scottnath** [comment]
Can type `gulp help` and paste the response here?

As to the error after 'patternlab-build-public', I'm going to work on getting PHP errors showing in the system. Most likely there is some twig template which is making Pattern Lab barf. Do you get php errors when you run this?

`php patternlab/core/console --generate`

**Comment by rebmullin** [comment]
I installed a new instance i get this error after i add a (HTML) pattern and run `gulp serve`. 

Note: Before I add the pattern it runs fine..

when I tried running `php patternlab/core/console --generate`, I get the following:
```php patternlab/core/console --generate
configuring pattern lab...
PHP Notice:  Undefined index: pathDash in /Users/rebeccamullin/Desktop/reb-pattern-library/patternlab/vendor/pattern-lab/core/src/PatternLab/PatternData/Exporters/DataLinkExporter.php on line 34
PHP Notice:  Undefined index: pathDash in /Users/rebeccamullin/Desktop/reb-pattern-library/patternlab/vendor/pattern-lab/core/src/PatternLab/PatternData/Exporters/DataLinkExporter.php on line 34
PHP Notice:  Undefined index: hidden in /Users/rebeccamullin/Desktop/reb-pattern-library/patternlab/vendor/pattern-lab/core/src/PatternLab/PatternData/Helpers/RawPatternHelper.php on line 44
PHP Notice:  Undefined index: pathName in /Users/rebeccamullin/Desktop/reb-pattern-library/patternlab/vendor/pattern-lab/core/src/PatternLab/PatternData/Helpers/RawPatternHelper.php on line 47
PHP Notice:  Undefined index: partial in /Users/rebeccamullin/Desktop/reb-pattern-library/patternlab/vendor/pattern-lab/core/src/PatternLab/PatternData/Helpers/RawPatternHelper.php on line 54
 wasn't found for loading. the given path: /Users/rebeccamullin/Desktop/reb-pattern-library/patternlab/source/_patterns/.twig```
or screenshot: http://grab.by/KOx2

**Comment by rebmullin** [comment]
ugh i think i added an html file which caused this : /   hopefully we can get rid of that soon : )

The only thing which is still is an issue is the last point noted above:

``` javascript
>gulp patterns-import-scottnath
Using gulpfile ~/Desktop/gen-new/gulpfile.js
Task 'patterns-import-scottnath' is not in your gulpfile 
Please check the documentation for proper gulpfile formatting
```

**Comment by scottnath** [comment]
@rebmullin that's what this PR does:
https://github.com/pattern-library/pattern-library-utilities/pull/17

Once that is merged, the system will no longer import those html files.

**Comment by scottnath** [comment]
@rebmullin 
cc: @e2tha-e @sergesemashko @conortm @beynya @nikkiana

This should now be fixed. Make sure and update the npm module `pattern-library-utilities` inside of every pattern library you've created. You can do this by running:

`npm install pattern-library-utilities --save-dev`

This should bring you up to version 0.1.8 of [pattern library utilities](https://github.com/pattern-library/pattern-library-utilities).

Version 0.1.8 blocks all importation of non-default file types.

Run

`gulp build` - to clean out patternlab

then

`gulp serve` - to re-import your library to patternlab and run your server.
